otsob/wmn4j

test/wmnlibmir/MonophonicPatternTest.java

Use standard JUnit instead of Jupiter

fixtest library import

---

src/wmnlibio/musicxml/DocHelper.java
src/wmnlibio/musicxml/MusicXmlReaderDom.java
src/wmnlibio/musicxml/MusicXmlTags.java
src/wmnlibnotation/noteobjects/Note.java
test/wmnlibio/musicxml/MusicXmlReaderDomTest.java
test/wmnlibnotation/builders/MeasureBuilderTest.java
test/wmnlibnotation/builders/NoteBuilderTest.java
test/wmnlibnotation/builders/PartBuilderTest.java
test/wmnlibnotation/noteobjects/NoteTest.java

Changed some methods that seemed relevant to return Optional instead of null, as requested in issue #7.

Issue #7: Change handling of null values

---

.travis.yml

Run maven install withouth javadoc generation on pull requests.

Issue#13: Configure travis CI for pull requests

---

.travis.yml
build-resources/travis/deploy_javadoc.sh

* Copy files from correct directory
* Produce javadoc only on successful builds

Issue #64: Fix travis javadoc generation

---

.travis.yml
pom.xml

Move to Java version 11 and update plugin versions.

Issue #65: Update java version to 11 and update plugin versions

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/mir/pattern_discovery/PointSet.java
src/main/java/org/wmn4j/notation/builders/MeasureBuilder.java
src/main/java/org/wmn4j/notation/elements/Chord.java
src/main/java/org/wmn4j/notation/elements/Duration.java
src/main/java/org/wmn4j/notation/elements/KeySignature.java
src/main/java/org/wmn4j/notation/elements/Pitch.java
src/main/java/org/wmn4j/notation/elements/TimeSignature.java
src/main/java/org/wmn4j/notation/iterators/PartWiseScoreIterator.java
src/main/java/org/wmn4j/notation/iterators/ScoreIterator.java
src/test/java/org/wmn4j/notation/builders/MeasureBuilderTest.java
src/test/java/org/wmn4j/notation/elements/ChordTest.java
src/test/java/org/wmn4j/notation/elements/DurationTest.java
src/test/java/org/wmn4j/notation/elements/KeySignatureTest.java
src/test/java/org/wmn4j/notation/elements/PitchTest.java
src/test/java/org/wmn4j/notation/elements/ScoreTest.java
src/test/java/org/wmn4j/notation/elements/TimeSignatureTest.java
src/test/java/org/wmn4j/notation/iterators/PartWiseScoreIteratorTest.java

* Use get in getters
* Use is for methods that return boolean
* Replace use of abbreviations with whole words

Issue #51: Improve method and parameter naming

---

src/main/java/org/wmn4j/io/musicxml/DocHelper.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReader.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriter.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/io/musicxml/package-info.java

* Unify the format of the javadoc comments
* Remove author tags because this is no longer supposed to be a single person project

Issue #76: Clean up javadocs in IO package

---

src/main/java/org/wmn4j/notation/elements/Measure.java
src/main/java/org/wmn4j/notation/elements/MultiStaffPart.java
src/main/java/org/wmn4j/notation/elements/Part.java
src/main/java/org/wmn4j/notation/elements/SingleStaffPart.java
src/main/java/org/wmn4j/notation/elements/TimeSignatures.java
src/main/java/org/wmn4j/notation/iterators/MeasureIterator.java
src/main/java/org/wmn4j/notation/iterators/PartIterator.java
src/main/java/org/wmn4j/notation/iterators/PartWiseScoreIterator.java
src/main/java/org/wmn4j/notation/iterators/ScoreIterator.java
src/test/java/org/wmn4j/notation/elements/MeasureTest.java

* Move all iterator definitions to the iterators package
* Make implementations private

Issue#34: Unify the placement and style of notation iterators

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/notation/elements/Score.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/notation/builders/ScoreBuilderTest.java
src/test/java/org/wmn4j/notation/elements/ScoreTest.java

Implements issue #26.
Change score name to title and add subtitle to attributes.

Issue#26: Add attributes to Score

---

src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/resources/musicxml/pickup_measure_test.xml

Adds test cases and a test file for reading MusicXML with pickup measure.

Issue #3: Add tests for reading MusicXML with pickup measure

---

.travis.yml
build.gradle

Move to Java 12 and build only on OpenJDK from now on.

Update to Java 12

---

src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java

Having access to the MusicXML file checks would help with testing MusicXmlWriterDom.

Refactor MusicXML file checks to separate class

---

src/main/java/org/wmn4j/mir/PatternBuilder.java
src/test/java/org/wmn4j/mir/PatternBuilderTest.java

Implement pattern builder that can be used for building monophonic patterns.

Issue #5: Add pattern builder

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/resources/musicxml/clef_change_where_note_in_another_voice_carries_over.xml

Fixes the bug with clef changes that occur while a note carries over the clef changes (issue #117).
Fixes a couple of small issues with MusicXmlReaderDom code.

Issue #117: Fix clef change bug

---

src/main/java/org/wmn4j/mir/MonophonicPattern.java
src/main/java/org/wmn4j/mir/PatternBuilder.java
src/main/java/org/wmn4j/mir/PolyphonicPattern.java
src/test/java/org/wmn4j/mir/PatternBuilderTest.java
src/test/java/org/wmn4j/mir/PatternTest.java
src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java

Implements the rest of issue #6 
* Implement equalsTranspositionally and equalsInDurations in PolyphonicPattern
* Add polyphonic pattern creation to PatternBuilder

Issue #6: Finish up polyphonic pattern handling

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java

Implements issue #38 
Write markings (slur, glissando) into MusicXML files.

Issue #38: Write markings into MusicXML

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriter.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java

Implements issue #19 
Adds MusicXmlWriter for writing patterns to MusicXML.
Currenlty supports only patterns with a single voice.

Issue #19: Add writing of single voice patterns to MusicXML

---

src/main/java/org/wmn4j/io/ScoreReader.java
src/main/java/org/wmn4j/io/ScoreWriter.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReader.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriter.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/builders/PartBuilder.java
src/main/java/org/wmn4j/notation/elements/SingleStaffPart.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
src/test/java/org/wmn4j/notation/TestHelper.java
src/test/java/org/wmn4j/notation/elements/SingleStaffPartTest.java

Implements issue #20 and a bit more
* Implement writing patterns with multiple voice into formatted MusicXML files
* Unify the interfaces of reading and writing MusicXML

Issue #20: Write multivoice patterns to MusicXML

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/mir/MonophonicPattern.java
src/main/java/org/wmn4j/mir/Pattern.java
src/main/java/org/wmn4j/mir/PatternBuilder.java
src/main/java/org/wmn4j/mir/PolyphonicPattern.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDomTest.java
src/test/java/org/wmn4j/mir/MonophonicPatternTest.java
src/test/java/org/wmn4j/mir/PatternBuilderTest.java
src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java

Implement issue #138 
Add possibility of creating patterns with names and labels.
Write the pattern name and labels to MusicXml.

Enable naming and labeling Patterns

---

src/main/java/org/wmn4j/mir/PatternOccurrence.java
src/main/java/org/wmn4j/mir/PatternPosition.java
src/main/java/org/wmn4j/mir/pattern_discovery/NoteEventVector.java
src/main/java/org/wmn4j/mir/pattern_discovery/PointSet.java
src/main/java/org/wmn4j/notation/elements/MultiStaffPart.java
src/main/java/org/wmn4j/notation/elements/Part.java
src/main/java/org/wmn4j/notation/elements/Score.java
src/main/java/org/wmn4j/notation/elements/SingleStaffPart.java
src/main/java/org/wmn4j/notation/elements/Staff.java
src/main/java/org/wmn4j/notation/iterators/PartWiseScoreIterator.java
src/main/java/org/wmn4j/notation/iterators/Position.java
src/main/java/org/wmn4j/notation/iterators/ScoreIterator.java
src/main/java/org/wmn4j/notation/iterators/ScorePosition.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/mir/PatternPositionTest.java
src/test/java/org/wmn4j/notation/elements/ScoreTest.java
src/test/java/org/wmn4j/notation/iterators/PartWiseScoreIteratorTest.java
src/test/resources/musicxml/basic_pattern_position_test.xml
src/test/resources/musicxml/multi_part_pattern_position_test.xml

Implements issue #21 
* Add class for referring to the position of a pattern in a score
* Add method to Score for getting the pattern referenced by a pattern position

Add handling of pattern positions in scores

---

README.md
build-resources/checkstyle/checkstyle.xml
build.gradle
gradle.properties

Fixes build problems caused by changes to gradle file and updates readme.

Release fixes

---

README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/notation/Score.java
src/test/java/org/wmn4j/TestHelper.java

Fixes various issues in the initial beta release of the project.

Patch ups to 0.1.0

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/Articulation.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/resources/musicxml/articulations.xml

Implements issue #155 
Adds the remaining articulations supported by MusicXml 3.1 to wmn4j and functionality to read and write musicxml files with these articulations.

Issue #155: Support all articulations that are available in MusicXML 3.1

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/TimeSignature.java
src/main/java/org/wmn4j/notation/TimeSignatures.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/notation/TimeSignatureTest.java
src/test/resources/musicxml/timesigs.xml

Addresses issue #159 
* Add way to handle all time signature symbols in MusicXml
* Add reading time signature symbols from MusicXml
* Add writing time signature symbols into MusicXml

Add support for time signature symbols

---

LICENSE.txt
README.md
build.gradle
gradle.properties
src/main/java/org/wmn4j/io/musicxml/DurationAppearanceProvider.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/Duration.java
src/main/java/org/wmn4j/notation/Durations.java
src/main/java/org/wmn4j/notation/MeasureBuilder.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/Score.java
src/main/java/org/wmn4j/notation/TimeSignature.java
src/test/java/org/wmn4j/io/musicxml/DurationAppearanceProviderTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
src/test/java/org/wmn4j/mir/discovery/PointSetTest.java
src/test/java/org/wmn4j/notation/DurationTest.java
src/test/java/org/wmn4j/notation/ScoreTest.java
src/test/java/org/wmn4j/notation/TimeSignatureTest.java
src/test/resources/musicxml/tuplet_test.musicxml

Addresses issue #123 
* Add tuplet information handling to Duration
* Add testing whether created duration is expressible in western music notation
* Add method for decomposing a duration into expressible durations
* Read duration appearances from MusicXML
* Use duration appearance information when outputting MusicXML

Add appearance information to Duration

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/main/java/org/wmn4j/notation/Ornament.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
src/test/java/org/wmn4j/notation/NoteBuilderTest.java
src/test/java/org/wmn4j/notation/NoteTest.java
src/test/java/org/wmn4j/notation/OrnamentTest.java
src/test/resources/musicxml/ornament_test.musicxml

Addresses issue #170 
* Adds support for basic ornament types

Add basic ornament handling

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/io/musicxml/TypeToDurationConverter.java
src/main/java/org/wmn4j/notation/ConnectableBuilder.java
src/main/java/org/wmn4j/notation/GraceNote.java
src/main/java/org/wmn4j/notation/GraceNoteBuilder.java
src/main/java/org/wmn4j/notation/Notation.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/main/java/org/wmn4j/notation/Ornament.java
src/main/java/org/wmn4j/notation/Ornamental.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
src/test/java/org/wmn4j/notation/GraceNoteBuilderTest.java
src/test/java/org/wmn4j/notation/GraceNoteTest.java
src/test/java/org/wmn4j/notation/NotationTest.java
src/test/java/org/wmn4j/notation/NoteBuilderTest.java
src/test/java/org/wmn4j/notation/NoteTest.java
src/test/java/org/wmn4j/notation/OrnamentTest.java
src/test/resources/musicxml/grace_note_test.musicxml

Addresses part of issue #166 
* Add types for handling grace notes
* Add MusicXML IO support for grace notes

Add grace note handling

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
src/main/java/org/wmn4j/notation/Chord.java
src/main/java/org/wmn4j/notation/GenericChord.java
src/main/java/org/wmn4j/notation/GraceNote.java
src/main/java/org/wmn4j/notation/GraceNoteBuilder.java
src/main/java/org/wmn4j/notation/GraceNoteChord.java
src/main/java/org/wmn4j/notation/GraceNoteChordBuilder.java
src/main/java/org/wmn4j/notation/Notation.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/main/java/org/wmn4j/notation/Ornament.java
src/main/java/org/wmn4j/notation/OrnamentalBuilder.java
src/main/java/org/wmn4j/notation/Pitched.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
src/test/java/org/wmn4j/notation/GraceNoteChordBuilderTest.java
src/test/java/org/wmn4j/notation/GraceNoteChordTest.java
src/test/java/org/wmn4j/notation/NoteBuilderTest.java
src/test/java/org/wmn4j/notation/NoteTest.java
src/test/java/org/wmn4j/notation/OrnamentTest.java
src/test/resources/musicxml/grace_note_chord_test.musicxml

Closes #166 
* Add type for grace note chords
* Add MusicXML IO support for grace note chords
* Use all ornaments in Note equality comparisons

Add support for grace note chords

---

src/main/java/org/wmn4j/mir/Pattern.java
src/main/java/org/wmn4j/mir/PatternsToScoreConverter.java
src/test/java/org/wmn4j/mir/PatternTest.java

* Enable creating a Score from a collection of Patterns

Patterns to score

---

src/main/java/org/wmn4j/mir/discovery/GeometricPatternDiscovery.java
src/main/java/org/wmn4j/notation/SelectionImpl.java
src/main/java/org/wmn4j/notation/access/Selection.java
src/main/java/org/wmn4j/representation/geometric/PointPattern.java
src/main/java/org/wmn4j/representation/geometric/PointSet.java
src/test/java/org/wmn4j/mir/discovery/SiatechfTest.java
src/test/java/org/wmn4j/notation/ScoreTest.java
src/test/java/org/wmn4j/notation/SelectionImplTest.java
src/test/java/org/wmn4j/representation/geometric/PointPatternTest.java
src/test/java/org/wmn4j/representation/geometric/PointSetTest.java

Closes #188 
* Enable creating PointSet<Point2D>s from Selections
* Enable creating PointPattern<Point2D>s from Patterns

Patterns and selections to pointset

---

src/main/java/org/wmn4j/io/musicxml/MusicXmlReader.java
src/main/java/org/wmn4j/io/musicxml/StaxReader.java

* Check the file extensions of MusicXML files
* Read the actual file path inside mxl/zip-archive from META-INF
* Check whether file is compressed using media-type

Improve compressed MusicXML reading

---

src/main/java/org/wmn4j/io/musicxml/CompressedMxl.java
src/main/java/org/wmn4j/io/musicxml/DurationAppearanceWriter.java
src/main/java/org/wmn4j/io/musicxml/IndentingXmlStreamWriter.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlReader.java
src/main/java/org/wmn4j/io/musicxml/MusicXmlWriter.java
src/main/java/org/wmn4j/io/musicxml/NotationWriteResolver.java
src/main/java/org/wmn4j/io/musicxml/StaxReader.java
src/main/java/org/wmn4j/io/musicxml/StaxWriter.java
src/main/java/org/wmn4j/notation/Measure.java
src/main/java/org/wmn4j/notation/PartwisePositionalIterator.java
src/main/resources/org/wmn4j/io/musicxml/musicxml.xsd
src/main/resources/org/wmn4j/io/musicxml/xlink.xsd
src/main/resources/org/wmn4j/io/musicxml/xml.xsd
src/test/java/org/wmn4j/io/musicxml/StaxWriterTest.java
src/test/java/org/wmn4j/notation/PartwisePositionalIteratorTest.java
src/test/resources/musicxml/empty_measure_iteration_test.musicxml

* Avoid producing empty elements and unnecessary in MusicXML
* Add indeting option in writing

Add compressed MusicXML output

---

README.md
examples/InputOutputExample.java
examples/ScoreAccessExample.java
examples/ScoreBuildingExample.java

Add simple examples

---

examples/ScoreBuildingExample.java
src/main/java/org/wmn4j/analysis/harmony/ChromagramBuilder.java
src/main/java/org/wmn4j/mir/PatternBuilder.java
src/main/java/org/wmn4j/notation/ChordBuilder.java
src/main/java/org/wmn4j/notation/ConnectableBuilder.java
src/main/java/org/wmn4j/notation/DurationalBuilder.java
src/main/java/org/wmn4j/notation/GraceNoteBuilder.java
src/main/java/org/wmn4j/notation/GraceNoteChordBuilder.java
src/main/java/org/wmn4j/notation/MeasureBuilder.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/main/java/org/wmn4j/notation/PartBuilder.java
src/main/java/org/wmn4j/notation/RestBuilder.java
src/main/java/org/wmn4j/notation/ScoreBuilder.java

* Enable chaining of method calls in all builders
* Consistently return the value directly in buidlers (no optionals)

Builder improvements

---

build.gradle
src/main/java/org/wmn4j/io/musicxml/DurationAppearanceWriter.java
src/main/java/org/wmn4j/io/musicxml/PartContext.java
src/main/java/org/wmn4j/io/musicxml/StaxReader.java
src/main/java/org/wmn4j/io/musicxml/StaxWriter.java
src/main/java/org/wmn4j/io/musicxml/Tags.java
src/main/java/org/wmn4j/io/musicxml/Transforms.java
src/main/java/org/wmn4j/notation/GraceNote.java
src/main/java/org/wmn4j/notation/GraceNoteBuilder.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/main/java/org/wmn4j/notation/techniques/ComplexTechnique.java
src/main/java/org/wmn4j/notation/techniques/NumericTechnique.java
src/main/java/org/wmn4j/notation/techniques/Technique.java
src/main/java/org/wmn4j/notation/techniques/TextualTechnique.java
src/main/java/org/wmn4j/notation/techniques/package-info.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/StaxReaderTest.java
src/test/java/org/wmn4j/io/musicxml/StaxWriterTest.java
src/test/java/org/wmn4j/notation/ChordTest.java
src/test/java/org/wmn4j/notation/GraceNoteBuilderTest.java
src/test/java/org/wmn4j/notation/GraceNoteTest.java
src/test/java/org/wmn4j/notation/NoteTest.java
src/test/java/org/wmn4j/notation/OrnamentTest.java
src/test/java/org/wmn4j/notation/techniques/TechniqueTest.java
src/test/resources/musicxml/techniques_test.musicxml

Add support for note-level playing technique markings.
Closes #175

Add support for note-level playing technique markings.

---

src/main/java/org/wmn4j/io/musicxml/LyricBuffer.java
src/main/java/org/wmn4j/io/musicxml/PartContext.java
src/main/java/org/wmn4j/io/musicxml/StaxReader.java
src/main/java/org/wmn4j/io/musicxml/StaxWriter.java
src/main/java/org/wmn4j/io/musicxml/Tags.java
src/main/java/org/wmn4j/io/musicxml/Transforms.java
src/main/java/org/wmn4j/notation/GraceNote.java
src/main/java/org/wmn4j/notation/GraceNoteBuilder.java
src/main/java/org/wmn4j/notation/Lyric.java
src/main/java/org/wmn4j/notation/Note.java
src/main/java/org/wmn4j/notation/NoteBuilder.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/StaxReaderTest.java
src/test/java/org/wmn4j/io/musicxml/StaxWriterTest.java
src/test/java/org/wmn4j/notation/ChordTest.java
src/test/java/org/wmn4j/notation/LyricTest.java
src/test/java/org/wmn4j/notation/NoteTest.java
src/test/resources/musicxml/lyrics_test.musicxml

- Add type for lyrics
- Add MusicXML IO for lyrics

Add support for lyrics

---

src/main/java/org/wmn4j/io/musicxml/PartContext.java
src/main/java/org/wmn4j/io/musicxml/StaxReader.java
src/main/java/org/wmn4j/io/musicxml/StaxWriter.java
src/main/java/org/wmn4j/io/musicxml/Tags.java
src/main/java/org/wmn4j/io/musicxml/Transforms.java
src/main/java/org/wmn4j/mir/PatternsToScoreConverter.java
src/main/java/org/wmn4j/notation/ChordSymbol.java
src/main/java/org/wmn4j/notation/ChordSymbolBuilder.java
src/main/java/org/wmn4j/notation/Measure.java
src/main/java/org/wmn4j/notation/MeasureBuilder.java
src/main/java/org/wmn4j/notation/Pitch.java
src/main/java/org/wmn4j/notation/PitchName.java
src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
src/test/java/org/wmn4j/io/musicxml/StaxReaderTest.java
src/test/java/org/wmn4j/io/musicxml/StaxWriterTest.java
src/test/java/org/wmn4j/notation/ChordSymbolBuilderTest.java
src/test/java/org/wmn4j/notation/ChordSymbolTest.java
src/test/java/org/wmn4j/notation/MeasureBuilderTest.java
src/test/java/org/wmn4j/notation/MeasureTest.java
src/test/java/org/wmn4j/notation/PitchTest.java
src/test/resources/musicxml/chord_symbol_test.musicxml

Closes #158 
- Add type for chord symbols
- Add MusicXML IO for chord symbols

Add support for chord symbols

---

gradle.properties
src/main/java/org/wmn4j/notation/PartwisePositionIterator.java
src/main/java/org/wmn4j/notation/Score.java
src/main/java/org/wmn4j/notation/SelectionImpl.java
src/main/java/org/wmn4j/notation/access/PositionIterator.java
src/main/java/org/wmn4j/notation/access/Positional.java
src/main/java/org/wmn4j/notation/access/PositionalEnumerator.java
src/main/java/org/wmn4j/notation/access/Selection.java
src/main/java/org/wmn4j/representation/geometric/PointSet.java
src/test/java/org/wmn4j/io/musicxml/StaxWriterTest.java
src/test/java/org/wmn4j/mir/PatternTest.java
src/test/java/org/wmn4j/notation/PartwisePositionIteratorTest.java
src/test/java/org/wmn4j/notation/ScoreTest.java
src/test/java/org/wmn4j/notation/SelectionImplTest.java

- Enable iterating durationals along with their positions ("enumerate")
- Provide streams to the contents of selections and scores.

Enumeration and streams

---

src/main/java/org/wmn4j/mir/PatternPosition.java
src/main/java/org/wmn4j/mir/search/PointSetPatternMatch.java
src/main/java/org/wmn4j/mir/search/PointSetSearch.java
src/main/java/org/wmn4j/mir/search/Search.java
src/main/java/org/wmn4j/mir/search/package-info.java
src/main/java/org/wmn4j/representation/geometric/PointPattern.java
src/main/java/org/wmn4j/representation/geometric/PointSet.java
src/test/java/org/wmn4j/mir/PatternPositionTest.java
src/test/java/org/wmn4j/mir/search/PointSetPatternMatchTest.java
src/test/java/org/wmn4j/mir/search/PointSetSearchTest.java
src/test/java/org/wmn4j/representation/geometric/PointPatternTest.java
src/test/resources/musicxml/search/pattern_search_test.musicxml

- Closes #189 
- Add search using point-set pattern matching

Add pattern search
