- pom.xml
Implements #46. The locale affects the language inside html tag in the beginning of the html files.
> #46: Use en_US locale in maven-javadoc-plugin

- pom.xml
Implements issue #48. Removing timestamps makes it easier to see what parts of the documentation have changed when regenerating.
> #48: Use notimestamp=true in maven-javadoc-plugin

- src/main/java/org/wmn4j/notation/elements/Pitch.java
Refactored the Pitch Base enum to define pitch base as integer, and the toInt method to use this number, as noted in the TODO comment.
> Refactor Pitch Base enum to define pitch base as int

- .travis.yml
- pom.xml
Issue #64: Add javadoc creation to travis and add default github pages deployment configuration.
> Issue #64: Add javadoc creation and deployment to travis 

- src/main/java/org/wmn4j/notation/elements/Note.java
- src/main/java/org/wmn4j/notation/elements/Pitched.java
Add an interface for pitched notation elements and have Note implement the interface (it is currently the only pitched notation element supported by wmn4j).
> Issue #30: Add interface for pitched notation elements

- src/main/java/org/wmn4j/notation/builders/ChordBuilder.java
- src/main/java/org/wmn4j/notation/builders/DurationalBuilder.java
- src/main/java/org/wmn4j/notation/builders/MeasureBuilder.java
- src/main/java/org/wmn4j/notation/builders/NoteBuilder.java
- src/main/java/org/wmn4j/notation/builders/PartBuilder.java
- src/main/java/org/wmn4j/notation/builders/RestBuilder.java
- src/main/java/org/wmn4j/notation/elements/Measure.java
- src/main/java/org/wmn4j/notation/elements/MeasureAttributes.java
- src/test/java/org/wmn4j/notation/builders/MeasureBuilderTest.java
- src/test/java/org/wmn4j/notation/elements/MeasureAttributesTest.java
* Pad voices with rests if they don't fill the measure
* Trim excess durations from a measure
* Allow building measures without padding and trimming to allow pickup measures and the rare cases that a score contains a measure that has too many notes (those exist...).
> Issue #53: Finish up MeasureBuilder

- .gitignore
- src/main/java/org/wmn4j/io/ScoreReader.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlReader.java
A new interface is added for reading music notation files into Score objects. The existing MusicXmlReader interface extends the new interface and overlap is removed from MusicXmlReader. By implementing MusicXmlReader, MusicXmlReaderDom also implements ScoreReader.
> Issue #39: Add common interface for reading files into Score objects

- src/main/java/org/wmn4j/notation/builders/MeasureBuilder.java
- src/main/java/org/wmn4j/notation/builders/PartBuilder.java
- src/main/java/org/wmn4j/notation/elements/Measure.java
- src/main/java/org/wmn4j/notation/elements/MultiStaffPart.java
- src/test/java/org/wmn4j/notation/builders/MeasureBuilderTest.java
- src/test/java/org/wmn4j/notation/builders/PartBuilderTest.java
- src/test/java/org/wmn4j/notation/elements/MeasureTest.java
- src/test/java/org/wmn4j/notation/elements/MultiStaffPartTest.java
* Add methods for handling full measure rests.
* Pad shorter staves with full measure rests in part builder when creating multi staff parts.
> Issue #78: Ensure each staff of a MultiStaffPart has same number of measures

- src/main/java/org/wmn4j/notation/builders/PartBuilder.java
- src/main/java/org/wmn4j/notation/builders/ScoreBuilder.java
- src/test/java/org/wmn4j/notation/builders/PartBuilderTest.java
- src/test/java/org/wmn4j/notation/builders/ScoreBuilderTest.java
Add empty measures to the end of parts that are shorter than the longest part in the score being collected into a score builder. This is intended for ensuring that all parts have the same number of measures in a score that is built using a score builder.
> Issue #79: Ensure each part in a Score built with a ScoreBuilder has the same number of measures

- .travis.yml
On pull requests test that build succeeds on Open JDK11.
> Run builds on openjdk11 as well on Travis

- src/main/java/org/wmn4j/io/ParsingFailureException.java
- src/main/java/org/wmn4j/io/ScoreReader.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/java/org/wmn4j/notation/TestHelper.java
Implements issue #40 
Add exception type for parsing failures and throw that when parsing fails.
Throw IOException when IO fails.
> Issue #40: Specify more detailed exceptions for file reading and parsing

- src/main/java/org/wmn4j/io/musicxml/DocHelper.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/main/java/org/wmn4j/notation/elements/Score.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/java/org/wmn4j/notation/elements/ScoreTest.java
- src/test/resources/musicxml/attribute_reading_test.xml
Implements issue #25 
Adds support for reading
* Score title
* Movement title
* Composer
* Arranger
* Part name
* Abbrebiated part name
from MusicXML.
> Issue #25: Add reading of score and part attributes to MusicXML reader

- .travis.yml
Currently deployment is run twice for the different JDK versions that wmn4j is built with.
Restrict deployment to only OpenJDK11.
> Deploy javadocs only on OpenJDK builds

- src/main/java/org/wmn4j/notation/elements/Chord.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/java/org/wmn4j/notation/elements/ChordTest.java
- src/test/resources/musicxml/articulations.xml
Add access to articulations in chords.
Add test cases for reading multiple articulations for a single note from MusicXML.
Add test cases for reading articulations for a chord from MusicXML.
> Issue #31: Ensure supported articulations are read from MusicXML

- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/resources/musicxml/multi_staff_multi_voice_marking_test.xml
- src/test/resources/musicxml/single_staff_single_voice_marking_test.xml
Adds support for reading markings (slurs, glissando) from MusicXML. 
The implementation only supports markings that occur between notes in the same voice.
Handling of slurs that cross parts and voices is more complex and is to be handled in issue #109
> Issue #32: Add support for reading markings from MusicXML

- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriter.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/main/java/org/wmn4j/notation/elements/Clef.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
Support for writing some basic notation to MusicXML added. There are still some fairly basic things that need to be added, such as support for multistaff parts and adding the [type](http://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-type.htm) for notes (opening written MusicXML files with e.g. MuseScore doesn't quite work, because it shows each note as a quarter note even if their duration in MusicXML are set correctly). I still thought creating a pull request would be a good idea at this point to confirm that this is heading to the right direction :)
> Issue #4: Add support for writing basic notation to MusicXML

- build.gradle
Timestamps are not necessary for the html files in javadoc because the files are in Git.
> Remove timestamps from javadocs to avoid unnecessary changes

- src/main/java/org/wmn4j/mir/MonophonicPattern.java
- src/main/java/org/wmn4j/mir/Pattern.java
- src/main/java/org/wmn4j/mir/PolyphonicPattern.java
- src/test/java/org/wmn4j/mir/MonophonicPatternTest.java
Implements part of issue #5 
Adds an implementation with tests for checking if monophonic patterns equal in:
* pitch
* durations
* enharmonically in pitch 
* transpositionally in pitch 
--
The implementation of a pattern builder will be done in a separate pull request. This PR already got a bit out of hand in size.
> Issue #5: Implement monophonic pattern handling

- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
Continuation for issue #4: Add support for writing basic notation to MusicXML, this pull request adds support for clef changes that happen during the measure rather than just before it.
> Issue #4: Add support for writing mid-measure clef changes

- src/main/java/org/wmn4j/io/musicxml/DurationAppearanceProvider.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/test/java/org/wmn4j/io/musicxml/DurationAppearanceProviderTest.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
- src/test/resources/musicxml/basic_dotted_duration_appearances.xml
- src/test/resources/musicxml/basic_duration_appearances.xml
- src/test/resources/musicxml/tuplet_writing_test.xml
Implements issue #119 
Add support for writing the note appearance elements based on the duration of the note.
This does not ensure that the appearance of the note will remain the same 
as it was when read from a file, because the same mathematical duration of 
a note can be written in multiple ways (e.g. dotted eighth note triplet has the same duration as an eighth note).
If note appearance is to be kept unchanged, then the issue #123 needs to be implemented.
> Add note appearance elements when writing MusicXML

- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
Implements issue #36 
Write work title, movement title, composer, and arranger to MusicXML
if those are defined for the score.
Write part name abbreviation to MusicXML if it's present.
> Write score attributes and abbreviated part names to MusicXML

- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
Adds support for writing accent, staccato, tenuto and fermata articulations to MusicXML. MusicXML doesn't handle fermatas as articulations (like wmn4j does), so it needed some special treatment in the code.
> Issue #37: Add support for writing single note articulations into MusicXML

- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
- src/test/resources/musicxml/articulationsOnMultipleStaves.xml
Addition to the last pull request (#128) to ensure that articulations on multiple staves are written into valid MusicXML.
> Add test for writing articulations on multiple staves to MusicXML

- README.md
- build.gradle
- src/main/java/org/wmn4j/Wmn4j.java
- src/main/java/org/wmn4j/package-info.java
- src/test/java/org/wmn4j/Wmn4jTest.java
Implements issue #124 
Adds a programmatic way of accessing version number that is defined in the Gradle build file.
Updates version number to be 0.1-SNAPSHOT
> Issue #124: Provide unified way of handling version number

- src/main/java/org/wmn4j/mir/MonophonicPattern.java
- src/main/java/org/wmn4j/mir/Pattern.java
- src/main/java/org/wmn4j/mir/PatternBuilder.java
- src/main/java/org/wmn4j/mir/PolyphonicPattern.java
- src/test/java/org/wmn4j/mir/MonophonicPatternTest.java
- src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java
Implements part of issue #6 
Adds implementations for some of the comparison methods.
The implementations are not necessarily the fastest possible, they can be 
optimized in the future if necessary. The implementations for the rest will follow soon, I thought that splitting the changes would make them a bit easier to review :)
> Issue #6: Add implementation for some of the methods in PolyphonicPattern 

- src/main/java/org/wmn4j/Wmn4j.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlWriterDomTest.java
- src/test/java/org/wmn4j/notation/TestHelper.java
- src/test/java/org/wmn4j/notation/builders/ScoreBuilderTest.java
Implements issue #125 
Write basic encoding information to MusicXML when outputting.
Adds software name and encoding date to files.
> Issue #125: Write basic encoding information to MusicXml

- src/main/java/org/wmn4j/mir/PatternBuilder.java
- src/main/java/org/wmn4j/notation/builders/ChordBuilder.java
- src/main/java/org/wmn4j/notation/builders/NoteBuilder.java
- src/main/java/org/wmn4j/notation/builders/RestBuilder.java
- src/test/java/org/wmn4j/mir/PatternBuilderTest.java
- src/test/java/org/wmn4j/notation/builders/ChordBuilderTest.java
- src/test/java/org/wmn4j/notation/builders/NoteBuilderTest.java
- src/test/java/org/wmn4j/notation/builders/RestBuilderTest.java
For consistency with all other builders, use DurationalBuilder instead of Durational in PatternBuilder. Add constructors for DurationalBuilders so they can be created from an existing Durational.
> Issue #137: Use DurationalBuilder instead of Durational in PatternBuilder

- build.gradle
The jdk logger implementation is thread safe. Simple logger
might not be.
> Use slf4j with java.util.logging instead of simple

- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
The file exists check causes IOException to be thrown
only if file doesn't exist when the exception should
also be thrown if opening file fails due to lacking
permissions.
Also checking first for file properties and then
trying to open it is an antipattern because the
file may have changed between the check and
opening.
> Remove additional file exists check

- src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDom.java
- src/main/java/org/wmn4j/mir/MonophonicPattern.java
- src/main/java/org/wmn4j/mir/Pattern.java
- src/main/java/org/wmn4j/mir/PatternBuilder.java
- src/main/java/org/wmn4j/mir/PolyphonicPattern.java
- src/main/java/org/wmn4j/notation/builders/PartBuilder.java
- src/main/java/org/wmn4j/notation/elements/MultiStaffPart.java
- src/main/java/org/wmn4j/notation/elements/Part.java
- src/main/java/org/wmn4j/notation/elements/Score.java
- src/main/java/org/wmn4j/notation/elements/SingleStaffPart.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/mir/MonophonicPatternTest.java
- src/test/java/org/wmn4j/mir/PatternBuilderTest.java
- src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java
- src/test/java/org/wmn4j/notation/builders/ScoreBuilderTest.java
- src/test/java/org/wmn4j/notation/elements/MultiStaffPartTest.java
- src/test/java/org/wmn4j/notation/elements/ScoreTest.java
- src/test/java/org/wmn4j/notation/elements/SingleStaffPartTest.java
Use empty optional to denote the absence of a string value instead of using empty strings. This makes the absence of values a bit clearer.
> Use optionals for missing String values

- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
When writing patterns, it's possible that a note that ends
a marking is found but the note beginning the marking is not
included. In that case do not add any markings to MusicXML.
> Fix null pointer exception for marking with no beginning

- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/main/java/org/wmn4j/notation/Duration.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/java/org/wmn4j/notation/DurationTest.java
- src/test/resources/musicxml/dotted_note_test.musicxml
Addresses part of #123
Dot information is useful for note appearance inference. The dots
do not affect the use of Durations in computations.
> Add dot information to duration

- src/main/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/main/java/org/wmn4j/notation/Note.java
- src/main/java/org/wmn4j/notation/Pitch.java
- src/test/java/org/wmn4j/TestHelper.java
- src/test/java/org/wmn4j/analysis/harmony/ChromagramBuilderTest.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlPatternWriterDomTest.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
- src/test/java/org/wmn4j/mir/MonophonicPatternTest.java
- src/test/java/org/wmn4j/mir/PatternBuilderTest.java
- src/test/java/org/wmn4j/mir/PatternTest.java
- src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java
- src/test/java/org/wmn4j/mir/discovery/GeometricPatternDiscoveryTest.java
- src/test/java/org/wmn4j/mir/discovery/PointSetTest.java
- src/test/java/org/wmn4j/notation/ChordBuilderTest.java
- src/test/java/org/wmn4j/notation/ChordTest.java
- src/test/java/org/wmn4j/notation/MeasureBuilderTest.java
- src/test/java/org/wmn4j/notation/MeasureTest.java
- src/test/java/org/wmn4j/notation/NotationTest.java
- src/test/java/org/wmn4j/notation/NoteBuilderTest.java
- src/test/java/org/wmn4j/notation/NoteTest.java
- src/test/java/org/wmn4j/notation/PartBuilderTest.java
- src/test/java/org/wmn4j/notation/PitchTest.java
- src/test/java/org/wmn4j/notation/ScoreTest.java
- src/test/java/org/wmn4j/notation/SingleStaffPartTest.java
- src/test/java/org/wmn4j/notation/StaffTest.java
- src/test/java/org/wmn4j/notation/access/PartWiseScoreIteratorTest.java
Addresses issue #171 
Using enum enables extending accidental types to
half sharps etc. in the future.
> Change accidental to enum

- .travis.yml
- README.md
- build.gradle
Stick to LTS versions to enable proper interoperability
with other JVM languages.
> Use Java 11

- README.md
Wmn4j does expose an API but is supposed to also
contain the implementation, this library is more
descriptive than API.
> Use the term library instead of API

- gradle.properties
- src/main/java/org/wmn4j/io/musicxml/MusicXmlReaderDom.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlTags.java
- src/main/java/org/wmn4j/io/musicxml/MusicXmlWriterDom.java
- src/main/java/org/wmn4j/notation/Measure.java
- src/main/java/org/wmn4j/notation/MeasureAttributes.java
- src/main/java/org/wmn4j/notation/MeasureBuilder.java
- src/main/java/org/wmn4j/notation/Pitch.java
- src/main/java/org/wmn4j/notation/access/Offset.java
- src/main/java/org/wmn4j/notation/directions/Direction.java
- src/main/java/org/wmn4j/notation/directions/package-info.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlFileChecks.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlReaderDomTest.java
- src/test/java/org/wmn4j/io/musicxml/MusicXmlScoreWriterDomTest.java
- src/test/java/org/wmn4j/notation/MeasureAttributesTest.java
- src/test/java/org/wmn4j/notation/MeasureBuilderTest.java
- src/test/java/org/wmn4j/notation/access/OffsetTest.java
- src/test/java/org/wmn4j/notation/directions/DirectionTest.java
- src/test/resources/musicxml/directions_test.musicxml
* Adds support for directions which are measure level markings (not related to a specific note, e.g. dynamics, tempo)
* Support for text type markings is added (can be extended later for tempo etc.)
* MusicXML IO is added for directions
Partly implements #176
> Add support for text playing directions

- src/main/java/org/wmn4j/io/musicxml/PartContext.java
- src/main/java/org/wmn4j/io/musicxml/StaxReader.java
- src/test/java/org/wmn4j/io/musicxml/StaxReaderTest.java
- src/test/resources/musicxml/nonnumeric_measure_number.musicxml
MusicXML allows measure number attribute to
contain non-numeric characters, or even omit
numbers altogether.
> Fix handling of non-numeric measure numbers

- src/main/java/org/wmn4j/mir/PolyphonicPattern.java
- src/main/java/org/wmn4j/representation/geometric/Point2D.java
- src/test/java/org/wmn4j/mir/PolyphonicPatternTest.java
The translational and enharmonic equivalence comparisons
are easier to implement usint the point-pattern representations.
> Use point-patterns for polyphonic comparisons

- build.gradle
Depend only on the slf4j api and not any implementation so that users of wmn4j can configure
any slf4j compatible logger.
> Make logger implementation selectable
